name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      checks: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest selenium
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install Firefox
      run: |
        sudo apt-get update
        sudo apt-get install -y firefox
    - name: Install GeckoDriver
      run: |
        GECKODRIVER_VERSION="0.35.0"  # Adjust to the latest version if needed
        wget "https://github.com/mozilla/geckodriver/releases/download/v$GECKODRIVER_VERSION/geckodriver-v$GECKODRIVER_VERSION-linux64.tar.gz"
        tar -xzf geckodriver-v$GECKODRIVER_VERSION-linux64.tar.gz
        sudo mv geckodriver /usr/local/bin/
    - name: Check Firefox version
      run: firefox --version
    - name: Check Python and pip versions
      run: |
        python --version
        pip --version
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        python -m pytest --verbose --junit-xml=junit.xml
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: success() || failure() # always run
      with:
        report_path: '**/junit.xml'
        detailed_summary: true
        include_passed: true
